"""Streamlit chat UI for AIU Chat.

Thin presentation layer: it calls the agent's data path and renders prose, the
result table, and (when chart-worthy) a Plotly chart. It does not import DuckDB
or Ollama directly — everything goes through aiu_chat.agent.

Run: streamlit run app/streamlit_app.py
"""
from __future__ import annotations

import streamlit as st

from aiu_chat import config
from aiu_chat.agent.catalog import get_catalog
from aiu_chat.agent.chart import make_chart
from aiu_chat.agent.llm import OllamaClient, OllamaError
from aiu_chat.agent.orchestrator import answer


def _about():
    # Imported lazily; `streamlit run app/streamlit_app.py` puts app/ on sys.path.
    import about_page

    about_page.render()

st.set_page_config(page_title="Aviation Intelligence Chat", page_icon="✈️", layout="centered")

DISCLAIMER = (
    "Data © EUROCONTROL Aviation Intelligence Unit ([ansperformance.eu](https://ansperformance.eu)). "
    "**Unofficial tool — not affiliated with or endorsed by EUROCONTROL.** "
    "Answers are generated by a local model from the published data and may contain errors."
)


# Suggested topics shown when the chat is empty — one row of cards per theme,
# each with a few example questions that exercise the different sources.
SUGGESTIONS = [
    (
        "🟢 Live now (real-time)",
        [
            "How many aircraft are airborne right now?",
            "Which areas have the most delay right now?",
            "Are there active weather regulations now?",
        ],
    ),
    (
        "📅 Latest daily (D-1)",
        [
            "How many flights did France have on the latest day?",
            "What is the latest daily ATFM delay for DSNA?",
            "Latest punctuality at Heathrow?",
        ],
    ),
    (
        "📊 Historical (by year/month)",
        [
            "Which 5 states had the most CO2 emissions in 2024?",
            "Show EGLL airport traffic per year as a bar chart",
            "Which ANSP had the most en-route ATFM delay in 2025?",
        ],
    ),
    (
        "📖 NOP & methodology",
        [
            "What's the latest NOP weather advisory?",
            "What does ATFM stand for?",
            "How is additional ASMA time calculated?",
        ],
    ),
]


# Human-readable explanation of each route, shown so the user sees how (and why)
# the assistant answered.
ROUTE_INFO = {
    "data": ("📊 Historical data (SQL)",
             "Recognised a question about past figures → wrote SQL and ran it on the local datasets."),
    "concept": ("📖 Concept / methodology",
                "Recognised a definition/methodology question → searched the reference docs & PDFs."),
    "both": ("📊+📖 Data and concept",
             "Needed both a figure and an explanation → combined the data and concept paths."),
    "nop": ("📡 NOP messages",
            "Recognised an operational/NOP question → fetched and interpreted recent NOP messages."),
    "dataapp": ("📅 Latest daily (D-1)",
                "Recognised a request for recent daily figures → queried the EUROCONTROL Data App API (D-1)."),
    "nm_live": ("🟢 Real-time network",
                "Recognised a 'right now' question → fetched the live Network Manager snapshot."),
    "catalog": ("🗂️ Data catalogue",
                "Recognised a 'what data do you have' question → answered from the dataset catalogue."),
    "none": ("🚫 Out of scope",
             "Judged the question to be outside European air navigation performance → declined."),
}


@st.cache_resource(show_spinner=False)
def _catalog():
    return get_catalog()


@st.cache_resource(show_spinner=False)
def _client(tier: str, think: bool, num_ctx: int):
    """Cached per (tier, think, num_ctx) so changing the selector rebuilds it."""
    return OllamaClient.from_tier(tier, think=think, num_ctx=num_ctx)


def _render_turn(turn, idx):
    """Render a Turn: combined prose, optional chart + table + SQL, and sources.

    `idx` makes element keys unique across replayed turns — Streamlit raises
    StreamlitDuplicateElementId if two charts/dataframes share an auto-ID.
    """
    # Show how the question was routed (transparency into the agent's choice).
    label, why = ROUTE_INFO.get(turn.route, (turn.route, ""))
    if turn.standalone_question and turn.standalone_question != turn.question:
        why += f"\n\nInterpreted your question as: *{turn.standalone_question}*"
    st.caption(f"**Route:** {label}")
    if why:
        with st.expander("How I answered this"):
            st.markdown(why)

    st.markdown(turn.answer)

    data = turn.data
    if data is not None and data.result is not None and not data.result.dataframe.empty:
        df = data.result.dataframe
        # Chart first (if the spec is valid + chart-worthy), then the table.
        fig = make_chart(data.chart_spec, df)
        if fig is not None:
            st.plotly_chart(fig, use_container_width=True, key=f"chart_{idx}")
        st.dataframe(df, use_container_width=True, hide_index=True, key=f"df_{idx}")
        if data.result.truncated:
            st.caption(f"Showing first {data.result.row_count} rows.")
        if data.sql:
            with st.expander("Show SQL"):
                st.code(data.sql, language="sql")

    # Live NOP messages: show the underlying messages in an expander.
    if turn.nop is not None and turn.nop.messages:
        with st.expander(f"NOP messages ({len(turn.nop.messages)})"):
            for m in turn.nop.messages:
                st.markdown(f"**{m.type}** · {m.published}")
                st.text(m.text[:1500])
        st.caption("Source: EUROCONTROL Network Operations Portal (live)")

    # Data App figures: D-1 (latest daily), not real-time — note entity + date.
    if turn.dataapp is not None and turn.dataapp.result is not None:
        r = turn.dataapp.result
        st.caption(
            f"Source: EUROCONTROL Data App — {r.metric} for {r.entity.name}, "
            f"latest daily figures as of {r.sync_date} (D-1, not real-time)"
        )

    # NM live snapshot: genuinely real-time.
    if turn.nm_live is not None and turn.nm_live.snapshot is not None:
        st.caption("Source: EUROCONTROL Network Manager — live (real-time)")

    if turn.sources:
        seen = []
        for s in turn.sources:
            if s.source_url not in [u for _, u in seen]:
                seen.append((s.source_title, s.source_url))
        links = " · ".join(f"[{title}]({url})" for title, url in seen)
        st.caption(f"Sources: {links}")


def _render_suggestions():
    """Topic cards with example questions; clicking one asks it. Returns the
    chosen question, or None."""
    st.markdown("#### Try one of these")
    chosen = None
    cols = st.columns(len(SUGGESTIONS))
    for col, (topic, questions) in zip(cols, SUGGESTIONS):
        with col:
            st.markdown(f"**{topic}**")
            for j, q in enumerate(questions):
                if st.button(q, key=f"sugg_{topic}_{j}", use_container_width=True):
                    chosen = q
    return chosen


def _sidebar_controls():
    """Render the model controls and return (tier, think, num_ctx)."""
    with st.sidebar:
        st.subheader("Model")

        tier_keys = list(config.MODEL_TIERS)
        default_idx = tier_keys.index(config.DEFAULT_TIER) if config.DEFAULT_TIER in tier_keys else 0
        tier = st.radio(
            "Complexity",
            tier_keys,
            index=default_idx,
            format_func=lambda k: config.MODEL_TIERS[k]["label"],
        )
        st.caption(config.MODEL_TIERS[tier]["blurb"])

        think = st.toggle(
            "Thinking mode",
            value=config.OLLAMA_THINK,
            help="Let the model reason step-by-step before answering. More "
                 "thorough on hard questions, but noticeably slower.",
        )

        with st.expander("Advanced"):
            num_ctx = st.select_slider(
                "Context window (tokens)",
                options=[4096, 8192, 16384, 32768],
                value=config.OLLAMA_NUM_CTX,
                help="Larger uses more memory; our prompts are small, so the "
                     "default is usually fine.",
            )

        st.divider()
        st.caption(f"Serving via Ollama at `{config.OLLAMA_HOST}`")
        st.caption(
            "If a model isn't installed, pull it first: "
            f"`ollama pull {config.MODEL_TIERS[tier]['model']}`"
        )
    return tier, think, num_ctx


def main():
    st.title("✈️ Aviation Intelligence Chat")
    st.caption("Ask about European air navigation performance data.")

    try:
        catalog = _catalog()
    except FileNotFoundError as exc:
        st.error(f"{exc}")
        st.stop()

    tier, think, num_ctx = _sidebar_controls()

    # Chat history (Turn objects) lives in session state and feeds follow-ups.
    if "messages" not in st.session_state:
        st.session_state.messages = []  # list of {"role", "content", "turn"?}
    if "history" not in st.session_state:
        st.session_state.history = []  # list of Turn

    # Replay history. The message index gives every element a stable unique key.
    for i, msg in enumerate(st.session_state.messages):
        with st.chat_message(msg["role"]):
            if msg["role"] == "assistant" and msg.get("turn") is not None:
                _render_turn(msg["turn"], idx=i)
            else:
                st.markdown(msg["content"])

    # Suggestion cards while the conversation is empty (the "middle" of the chat).
    suggested = _render_suggestions() if not st.session_state.messages else None

    typed = st.chat_input("e.g. Which 5 states had the most CO2 emissions in 2024?")
    prompt = typed or suggested
    if prompt:
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            with st.spinner("Thinking… (choosing a source and gathering data)"):
                try:
                    turn = answer(
                        prompt,
                        history=st.session_state.history,
                        client=_client(tier, think, num_ctx),
                        catalog=catalog,
                    )
                except OllamaError as exc:
                    st.error(f"Could not reach the local model: {exc}")
                    turn = None
            if turn is not None:
                # This turn will occupy the next message slot; key by that index.
                _render_turn(turn, idx=len(st.session_state.messages))
                st.session_state.history.append(turn)
                st.session_state.messages.append(
                    {"role": "assistant", "content": turn.answer, "turn": turn}
                )
        # A suggestion click sets state mid-script; rerun so the cards disappear
        # and the new turn renders through the normal replay path.
        if suggested:
            st.rerun()

    st.divider()
    st.caption(DISCLAIMER)


# Explicit multi-page navigation so the sidebar labels are clean
# ("Aviation Intelligence Chat" / "About"), not derived from filenames.
_nav = st.navigation(
    [
        st.Page(main, title="Aviation Intelligence Chat", icon="✈️", default=True),
        st.Page(_about, title="About", icon="ℹ️"),
    ]
)
_nav.run()
