"""Streamlit chat UI for AIU Chat.

Thin presentation layer: it calls the agent's data path and renders prose, the
result table, and (when chart-worthy) a Plotly chart. It does not import DuckDB
or Ollama directly — everything goes through aiu_chat.agent.

Run: streamlit run app/streamlit_app.py
"""
from __future__ import annotations

import streamlit as st

from aiu_chat import config
from aiu_chat.agent.catalog import get_catalog
from aiu_chat.agent.chart import make_chart
from aiu_chat.agent.llm import OllamaClient, OllamaError
from aiu_chat.agent.text_to_sql import answer_data_question

st.set_page_config(page_title="AIU Chat", page_icon="✈️", layout="centered")

DISCLAIMER = (
    "Data © EUROCONTROL Aviation Intelligence Unit ([ansperformance.eu](https://ansperformance.eu)). "
    "**Unofficial tool — not affiliated with or endorsed by EUROCONTROL.** "
    "Answers are generated by a local model from the published data and may contain errors."
)


@st.cache_resource(show_spinner=False)
def _catalog():
    return get_catalog()


@st.cache_resource(show_spinner=False)
def _client():
    return OllamaClient()


def _render_answer(ans):
    """Render a DataAnswer: prose, optional chart, result table, and the SQL."""
    st.markdown(ans.answer)

    if ans.result is not None and not ans.result.dataframe.empty:
        df = ans.result.dataframe
        # Chart first (if the spec is valid + chart-worthy), then the table.
        fig = make_chart(ans.chart_spec, df)
        if fig is not None:
            st.plotly_chart(fig, use_container_width=True)
        st.dataframe(df, use_container_width=True, hide_index=True)
        if ans.result.truncated:
            st.caption(f"Showing first {ans.result.row_count} rows.")

    if ans.sql:
        with st.expander("Show SQL"):
            st.code(ans.sql, language="sql")


def main():
    st.title("✈️ AIU Chat")
    st.caption("Ask about European air navigation performance data.")

    try:
        catalog = _catalog()
    except FileNotFoundError as exc:
        st.error(f"{exc}")
        st.stop()

    with st.sidebar:
        st.subheader("Data")
        for d in catalog.datasets:
            st.markdown(f"**{d.title}**")
            st.caption(f"`{d.table}` · through {d.as_of or 'n/a'}")
        st.divider()
        st.caption(f"Model: `{config.MODEL_NAME}`")

    # Chat history lives in session state.
    if "messages" not in st.session_state:
        st.session_state.messages = []  # list of {"role", "content", "answer"?}

    # Replay history.
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            if msg["role"] == "assistant" and msg.get("answer") is not None:
                _render_answer(msg["answer"])
            else:
                st.markdown(msg["content"])

    prompt = st.chat_input("e.g. Which 5 states had the most CO2 emissions in 2024?")
    if prompt:
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            with st.spinner("Querying the data…"):
                try:
                    ans = answer_data_question(prompt, client=_client(), catalog=catalog)
                except OllamaError as exc:
                    st.error(f"Could not reach the local model: {exc}")
                    ans = None
            if ans is not None:
                _render_answer(ans)
                st.session_state.messages.append(
                    {"role": "assistant", "content": ans.answer, "answer": ans}
                )

    st.divider()
    st.caption(DISCLAIMER)


if __name__ == "__main__":
    main()
